### ISSUE TITLE
Bug when using jason-cli

### ISSUE THREAD

**Issue by nilsonLazarin** [jacamo-lang/mvn-repo#2]
Hello @jomifred,

Today a bug is occurring when using the [Jason-CLI (by chon repository version)](https://github.com/chon-group/dpkg-jason)...

Is related with the last update in 3.3.0-SNAPSHOT folder? [a1c02ea]

```console
nilson@dell:/tmp$ sudo apt install jason-cli
Lendo listas de pacotes... Pronto
Construindo árvore de dependências... Pronto
Lendo informação de estado... Pronto        
jason-cli is already the newest version (3.3.0-SNAPSHOT-240412).
0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 40 não atualizados.
nilson@dell:/tmp$ jason app create algoErrado
Creating directory algoErrado

You can run your application with:
   $ jason algoErrado/algoErrado.mas2j
nilson@dell:/tmp$ jason algoErrado/algoErrado.mas2j 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve io.github.jason-lang:jason-interpreter:3.3.0-SNAPSHOT.
     Required by:
         project :
      > No matching variant of io.github.jason-lang:jason-interpreter:3.3.0-SNAPSHOT was found. The consumer was configured to find a library for use during compile-time, compatible with Java 17, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally but:
          - Variant 'apiElements' capability io.github.jason-lang:jason-interpreter:3.3.0-SNAPSHOT declares a library for use during compile-time, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 21 and the consumer needed a component, compatible with Java 17
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
          - Variant 'runtimeElements' capability io.github.jason-lang:jason-interpreter:3.3.0-SNAPSHOT declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 21 and the consumer needed a component, compatible with Java 17
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 355ms
Error running 'gradle run'
nilson@dell:/tmp$ 

```

**Comment by nilsonLazarin** [comment]
If I change the repo to use the version of [69e273b](https://github.com/jacamo-lang/mvn-repo/tree/69e273bcc8db980bbc9b0610dccfc3e5475f9794), it run again.

Need I change the bin file in my project an up to Java 21?

![image](https://github.com/user-attachments/assets/3a23fa71-0d10-489d-8db8-d5221c6c92a6)

Thank you very much!

**Comment by jomifred** [comment]
Yes Nilson, for jason 3.3 we moved to java 21 (to use virtual threads instead of platform threads for the agents)

**Comment by nilsonLazarin** [comment]
@jomifred, we have a problem!

- When using the jason [main](https://github.com/jason-lang/jason) version, to try to generate a binary file...
 ![image](https://github.com/user-attachments/assets/bdd61ecb-fc49-423d-8f0b-08062905c441)

- I try to install the Java 17 too (together with java 21). In this case, a build was possible (I think that is jason 3.2), but jason-cli don't work
![image](https://github.com/user-attachments/assets/3890f844-6ea0-4a40-8a03-f229f6b0251a)

- Finally, using the [jason 3.3.0 pre-release](https://github.com/jason-lang/jason/releases/tag/v3.0.0-snapshot), bug again...
![image](https://github.com/user-attachments/assets/dc4cfaff-7508-443f-84b1-3bdb89eba6f5)

 Can you provide a new jason-cli binary, or instructions?
 
 Thank you very much!

**Comment by jomifred** [comment]
Hi Nilson, 

the plan is: current branch main still has jason 3.2, that uses java 17. The branch develop has the version 3.3, that uses java 21. Regarding the  pre-release, I have just updated it and it seems to work for Java 21.

I will also test on my side to see if I can reproduce the erros.

**Comment by nilsonLazarin** [comment]
Hello @jomifred ,

New Jason-CLI package available at: https://github.com/chon-group/dpkg-jason/releases/tag/jasoncli-20241017

Thank you!
